baseURL = 'https://wimpress.com/'
title = 'Martin Wimpress'

languageCode = 'en-gb'
DefaultContentLanguage = "en"

theme = 'freelancer'
summaryLength=40
paginate=9

enableEmoji = true
enableRobotsTXT = true

[social]
  twitter = 'm_wimpress'

[params]
  author = 'Martin Wimpress'
  description = 'Blog, Podcasts, Live Streams and Videos about Linux and Open Source with a focus on Ubuntu, Debian and NixOS.'
  tags = 'Linux, Open Source, Ubuntu, Debian, NixOS, nix, Desktop Linux, systemd, Containers, Virtualisation, OBS Studio, Live Stream, Twitch, YouTube, Podcast'
  tagLine = "INNOVATION - OPEN SOURCE - LEADERSHIP"
  aboutLeft = "Respected leader and innovator with a considerable breadth of IT competency, particularly Linux and Open Source. A proven track record of translating business requirements into IT solutions and well practiced with contemporary IT development and management methodologies. Logical approach to problem-solving, demonstrable record of creating novel and unique solutions."
  aboutRight = "Passionate Open Source advocate and Linux enthusiast. Proficient software developer using several languages. Contributor to many Open Source projects to retain and develop technical skill as an accomplished systems integrator and architect. Podcaster, Live Streamer and Community builder. Leads Ubuntu MATE, Ubuntu Member and Debian Maintainer."
  homePosts = 6
  homeProjects = 9
  heroWidth = 1280
  heroHeight = 720
  heroWidthSmall = 426
  heroHeightSmall = 240
  profileWidth = 528
  profileHeight = 560

[params.features]
  [params.features.comment]
    enable = true
    [params.features.comment.giscus]
      repo = "flexiondotorg/flexiondotorg.github.io"
      repoID = "R_kgDOIoJw9g"
      category = "Blog Comments"
      categoryID = "DIC_kwDOIoJw9s4CTG_3"
      theme = "light"
      map = "pathname"
      strict = 0
      reaction = 1
      metadata = 0
      inputPosition = "bottom"
      crossOrigin = "anonymous"

[params.sbform]
  token = "72ea1ec7-2670-4a14-a16a-155ce22f82e3"

[params.homebutton]
  text = "LinkedIn"
  link = "https://linkedin.com/in/martinwimpress"
  icon = "fa-linkedin"

# icon name without the 'fa-'
[[params.social]]
  icon      = "discord"
  icon_pack = "fab"
  url       = "https://wimpysworld.io/discord"
[[params.social]]
  icon      = "mastodon"
  icon_pack = "fab"
  url       = "https://fosstodon.org/@wimpy"
[[params.social]]
  icon      = "twitter"
  icon_pack = "fab"
  url       = "https://twitter.com/m_wimpress"
[[params.social]]
  icon      = "linkedin"
  icon_pack = "fab"
  url       = "https://linkedin.com/in/martinwimpress"

[[params.code]]
  icon      = "github"
  icon_pack = "fab"
  url       = "https://github.com/flexiondotorg"
[[params.code]]
  icon      = "ubuntu"
  icon_pack = "fab"
  url       = "https://launchpad.net/~flexiondotorg"

[[params.content]]
  icon      = "instagram"
  icon_pack = "fab"
  url       = "https://instagram.com/WimpysWorld"
[[params.content]]
  icon      = "twitch"
  icon_pack = "fab"
  url       = "https://twitch.tv/WimpysWorld"
[[params.content]]
  icon      = "youtube"
  icon_pack = "fab"
  url       = "https://youtube.com/WimpysWorld"
[[params.content]]
  icon      = "podcast"
  icon_pack = "fas"
  url       = "https://linuxdowntime.com"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[permalinks]
  posts = 'posts/:slug/'
  projects = 'projects/:slug/'

[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    [markup.goldmark.parser.attribute]
      block = true
[markup.highlight]
  style = 'rrt'
[markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[outputs]
    home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[sitemap]
  changefreq = 'weekly'
  priority = 0.8

[taxonomies]
  category = 'categories'
  tag = 'tags'
