baseURL = 'https://wimpress.com/'
title = "Wimpy's World"

languageCode = 'en-gb'
DefaultContentLanguage = "en"

theme = 'freelancer'
summaryLength=40
paginate=9

enableEmoji = true
enableRobotsTXT = true

[social]
  twitter = 'm_wimpress'

[params]
  author = 'Martin Wimpress'
  description = 'Blog, Podcasts, Live Streams and Videos about Linux and Open Source with a focus on Ubuntu, Debian and NixOS.'
  tags = 'Linux, Open Source, Ubuntu, Debian, NixOS, nix, Desktop Linux, systemd, Containers, Virtualisation, OBS Studio, Live Stream, Twitch, YouTube, Podcast, MATE Desktop'
  tagLine = "INNOVATION - OPEN SOURCE - LEADERSHIP"
  homePosts = 6
  homeProjects = 9
  heroWidth = 1280
  heroHeight = 720
  heroWidthSmall = 426
  heroHeightSmall = 240
  profileWidth = 528
  profileHeight = 560

[params.features]
  [params.features.comment]
    enable = true
    [params.features.comment.giscus]
      repo = "flexiondotorg/flexiondotorg.github.io"
      repoID = "R_kgDOIoJw9g"
      category = "Blog Comments"
      categoryID = "DIC_kwDOIoJw9s4CTG_3"
      theme = "light"
      map = "pathname"
      strict = 0
      reaction = 1
      metadata = 0
      inputPosition = "bottom"
      crossOrigin = "anonymous"

[params.sbform]
  token = "72ea1ec7-2670-4a14-a16a-155ce22f82e3"

[[params.social]]
  icon      = "fa-discord"
  icon_pack = "fab"
  label     = "Discord"
  url       = "https://wimpysworld.io/discord"
[[params.social]]
  icon      = "fa-mastodon"
  icon_pack = "fab"
  label     = "Mastodon"
  url       = "https://fosstodon.org/@wimpy"
[[params.social]]
  icon      = "fa-twitter"
  icon_pack = "fab"
  label     = "Twitter"
  url       = "https://twitter.com/m_wimpress"
[[params.social]]
  icon      = "fa-linkedin"
  icon_pack = "fab"
  label     = "LinkedIn"
  url       = "https://linkedin.com/in/martinwimpress"

[[params.code]]
  icon      = "fa-github"
  icon_pack = "fab"
  label     = "GitHub"
  url       = "https://github.com/flexiondotorg"
[[params.code]]
  icon      = "fa-ubuntu"
  icon_pack = "fab"
  label     = "Launchpad"
  url       = "https://launchpad.net/~flexiondotorg"

[[params.content]]
  icon      = "fa-instagram"
  icon_pack = "fab"
  label     = "Instagram"
  url       = "https://instagram.com/WimpysWorld"
[[params.content]]
  icon      = "fa-twitch"
  icon_pack = "fab"
  label     = "Twitch"
  url       = "https://twitch.tv/WimpysWorld"
[[params.content]]
  icon      = "fa-youtube"
  icon_pack = "fab"
  label     = "YouTube"
  url       = "https://youtube.com/WimpysWorld"
[[params.content]]
  icon      = "fa-podcast"
  icon_pack = "fas"
  label     = "Linux Downtime Podcast"
  url       = "https://linuxdowntime.com"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[permalinks]
  posts = 'posts/:slug/'
  projects = 'projects/:slug/'

[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    [markup.goldmark.parser.attribute]
      block = true
[markup.highlight]
  style = 'rrt'
[markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[outputs]
    home = ["HTML", "RSS", "JSON"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[sitemap]
  changefreq = 'weekly'
  priority = 0.8

[taxonomies]
  category = 'categories'
  tag = 'tags'
